#+TITLE: CV
#+AUTHOR: Ronak Cuthill
#+OPTIONS: toc:nil num:nil

* Objective Statement
Growth-oriented new graduate with a bachelors degree in math seeking to leverage strong analytical skills for formal verification of pre-silicon accelerator designs.

Interested in furthering my education in professional and academic settings to pursue a career in systems design of asymmetric multicore architectures in order to compensate for the problems that cannot be addressed through transistor miniaturization.

* Education
** B.Sc in Mathematics with Computer Science Minor at the University of Victoria - 2019 to 2023
- Understanding of data structures and algorithms, from linked lists to graphs to hash tries.
- Understanding of computer architecture, interrupts, and embedded peripherals.
- Design of digital circuits from a logic to RTL level, with limited HDL experience.
- Experience in linear algebra, combinatorics, and graph theory
- Led efforts to create online study groups during the pandemic to support the education of my peers.
- Can confidently analyze data using statistical methods.

* Projects
- Wrote a general purpose buddy block memory allocator and mark and sweep garbage collector in C.
- Created a compiler with a bytecode backend to a self-created virtual machine.
- Programmed an STM32 on bare metal to blink a light and accept input.
- Studied formal verification in Verilog.
- Implemented a B-tree based in-memory database supporting insertion and selection.

* Professional/Personal Experience
** Driver at You Move Me Victoria - 2022
- Rapidly ascended the responsibility ladder at You Move Me Victoria from a laborer to team leader position in under two months by leading my teams to reduce packing time on the job.

** Scholar Athlete, and Entrepreneur at South Lakes High School - 2015 to 2018
- Took initiative in my education during childhood to pursure university courses in mathematics before high-school.
- Led my high-school shotput team to a higher level of competition - increased team size to a dozen individuals and brought five of them to compete on the state level.
- Started a landscaping and hauling business with temporary employees to address the needs of my local community.

* Skills
- Problem-solving
- Leadership
- Teamwork
- Curiosity
- C/Assembler
- Verilog
- Python
- Forth
- Haskell
- Git
- Emacs
- Linux
- Nix
- Autotools

* Contact
ronak.cuthill@gmail.com

(778)-700-1618

http://github.com/ton2790
